import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {tableSpecifications,exportTables} from './verge_search_csv.mjs';
const [input,output]=process.argv.slice(2);
if (!input || !output) throw new Error('Synthetic input and output directory required');
const bundle=JSON.parse(await fs.readFile(input,'utf8'));assert.equal(bundle.synthetic,true);
const specs=tableSpecifications(bundle);assert.equal(specs.length,6);
assert.deepEqual(specs.map(s=>s[2].length),[456,234,24,6,6,36]);
const missing=structuredClone(bundle);missing.analysis.endpoint_rows.pop();
assert.throws(()=>tableSpecifications(missing),/Incomplete/);
const nan=structuredClone(bundle);nan.analysis.endpoint_rows[0].observed_rate=NaN;
assert.throws(()=>tableSpecifications(nan),/non-scalar/);
const formula=structuredClone(bundle);formula.analysis.endpoint_rows[0].checkpoint='=BAD()';
assert.throws(()=>tableSpecifications(formula),/Formula-like/);
const provenance=structuredClone(bundle);delete provenance.synthetic;
assert.throws(()=>tableSpecifications(provenance),/provenance/);
const events=specs.find(s=>s[0]==='trajectory_events')[2];
assert.ok(events.every(e=>e.first_event_role===null && e.event_observed===false && e.right_censored===true));
const source=specs[0][2].find(r=>r.endpoint==='branch_endpoint');
assert.ok(source.source_artifact.includes('_b0/branches/0/target.jsonl'));
const receipt=await exportTables(bundle,output);
assert.equal(receipt.synthetic,true);assert.equal(receipt.search_block_complete,false);assert.equal(receipt.suite_complete,false);
assert.ok(receipt.tables.every(t=>t.typed_values_unchanged && t.preview_rendered && t.preview_columns===8));
console.log(JSON.stringify({synthetic_only:true,checks_passed:12,tables:receipt.tables,suite_complete:false}));
